### ISSUE TITLE
[Feature (Maybe)] Theme/Plugin Install Button

### ISSUE THREAD

**Issue by MintLily** [Davr1/powercord-plugin-cards#1]
With the plugins that allow us to one-click-install the item, is it possible to add that as a button?
I don't know how difficult it is, or if it's even possible to do, with only CSS; but that'd be a great addition.

**Comment by SammCheese** [comment]
That feature would require JS and cant be done with CSS alone

**Comment by Davr1** [comment]
Would definitely require a plugin.
I tried to do something similar with the "Apply snippet" button that you see in #css-snippets, but it doesn't add the element until you move your mouse over the message, and the hover states are also managed by javascript so it's hard to make a proper button.

**Comment by MintLily** [comment]
Darn, ok. It was worth an ask. Thanks.

**Comment by Davr1** [comment]
np ![:TohruThumbsUp:](https://cdn.discordapp.com/emojis/744282313197879317.gif?size=28)
